Enhancements to allow replaying messages and other stuff
ONSdigital/census-rm-exception-manager-2021 pull request #10
Opened 2020-06-08 12:41 UTC by NickGrantONS

# Motivation and Context
We're slowly improving the capabilities of our operational tooling. This wave of enhancement adds the ability to do various things, including replaying quarantined messages.

# What has changed
Added some new endpoints the the API.

# How to test?
Try quarantining a message, then replay it by hitting the `/replayquarantinedmessage/<id>` endpoint... the message should pop back onto the Rabbit queue it came from (but beware - it might get skipped again unless you reset the exception manager).

You can also try out the endpoints to get all the auto quarantine rules, or delete an auto quarantine rule, if that's your sort of thing.

# Links
Trello: https://trello.com/c/whSpMIJG

2020-06-08 12:42 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change Toolbox/Exception Manager so that it can replay quarantined messages from the DB](https://trello.com/c/whSpMIJG/1003-change-toolbox-exception-manager-so-that-it-can-replay-quarantined-messages-from-the-db)

2020-06-09 07:05 UTC, AdamHawtin requested changes
All seems to work, the name `InMemoryDatabase` was throwing me though.

2020-06-09 07:05 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/exceptionmanager/endpoint/AdminEndpoint.java
> +    inMemoryDatabase.deleteQuarantineRule(id);
`InMemoryDatabase` needs renaming, had me properly confused for a few minutes.

2020-06-09 07:50 UTC, AdamHawtin approved these changes

2020-06-09 11:20 UTC, hbrace approved these changes

2020-06-09 11:23 UTC, merged