reset only the messages that have been resolved
ONSdigital/census-rm-exception-manager-2021 pull request #15
Opened 2021-04-29 12:55 UTC by ryangrundy7

# Motivation and Context

Instead of resetting all of the bad message cache, we want to have an option to be able to remove only the bad messages that have been resolved and not seen in the last 5 minutes.
# What has changed

- Added optional parameter to reset method to be able to only reset the bad messages that have been resolved.

# How to test?

- run `mvn clean install`
- Run with toolbox PR
- Create some bad messages and "resolve" them (I did this by purging the DelayedRedeliveryQueue)
- Once purged, create some more bad messages. These ones should be repeatedly seen by the exception manager.
- Wait 5 minutes and in the message wizard, use the `Reset resolved bad messages` to remove them from the cache. The only bad messages left on the bad message wizard should be the ones after the purge.

# Links

[Trello](https://trello.com/c/48p2DeUH/)

2021-04-29 12:56 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exception Manager reset only the 'bad' messages not seen for 5 minutes - i.e. get rid of ones which have resolved themselves (5)](https://trello.com/c/48p2DeUH/2235-exception-manager-reset-only-the-bad-messages-not-seen-for-5-minutes-ie-get-rid-of-ones-which-have-resolved-themselves-5)

2021-04-29 13:03 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/exceptionmanager/endpoint/AdminEndpoint.java
> +      @RequestParam(value = "resetOldMessages", required = false) boolean resetOldMessages) {
Could we make this param the age of message to reset? Then, if we ever want to change it, it can be done from the caller rather than a code change in exception manager

2021-04-29 15:08 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/exceptionmanager/persistence/CachingDataStore.java
> +  public void reset(Boolean resetOldMessages) {
you should avoid mix & match of `boolean` and `Boolean`. Just use `boolean` unless you explicitly want to deal with `null` as an option

2021-04-29 15:08 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/exceptionmanager/persistence/CachingDataStore.java
> +        if (timeDifference > 300) {
would be nice to have this configurable in `application.yml`

2021-04-29 15:24 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/exceptionmanager/persistence/CachingDataStore.java
> +            Instant.now().getEpochSecond() - item.getValue().getLastSeen().getEpochSecond();
Consider this preferred style:

```java
        Instant timeCutoff = Instant.now().minusSeconds(300);

        if (item.getValue().getLastSeen().isAfter(timeCutoff)) {
```

2021-04-29 15:27 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/exceptionmanager/endpoint/AdminEndpoint.java
> +      @RequestParam(value = "resetOldMessages", required = false) boolean resetOldMessages) {
This would actually be way nicer if it was:
`@RequestParam(value = "lastSeenCutoffSeconds", required = false) Optional<Integer> lastSeenCutoffSeconds)`

2021-04-29 15:28 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/exceptionmanager/endpoint/AdminEndpoint.java
> +      @RequestParam(value = "resetOldMessages", required = false) boolean resetOldMessages) {
What he said...

This would actually be way nicer if it was:
`@RequestParam(value = "lastSeenCutoffSeconds", required = false) Optional<Integer> lastSeenCutoffSeconds)`

2021-04-29 15:29 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/exceptionmanager/persistence/CachingDataStore.java
> +        if (timeDifference > 300) {
or passed from the caller, in fact would be best

2021-04-30 10:57 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/exceptionmanager/endpoint/AdminEndpoint.java
> +      @RequestParam(value = "resetOldMessages", required = false) boolean resetOldMessages) {
Passing in cut off time now

2021-04-30 10:57 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/exceptionmanager/persistence/CachingDataStore.java
> +  public void reset(Boolean resetOldMessages) {
Fixed this to now pass in an `Optional<Integer>`

2021-04-30 13:20 UTC, NickGrantONS approved these changes
Great! 👍

2021-05-04 06:39 UTC, AdamHawtin requested changes
Looks good, needs some tests

2021-05-04 14:08 UTC, AdamHawtin commented on src/test/java/uk/gov/ons/census/exceptionmanager/persistence/CachingDataStoreTest.java
>      assertThat(underTest.getBadMessageReports("test message hash")).isEmpty();
duplicate line

2021-05-05 07:34 UTC, AdamHawtin approved these changes

2021-05-05 08:40 UTC, merged